// app/guest/screens/recommendation.tsx
import * as FileSystem from 'expo-file-system';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import axios from 'axios';
import React, { useEffect, useState } from 'react';
import {
  Alert,
  Image,
  Platform,
  ScrollView,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from 'react-native';
import { useRouter } from 'expo-router';
import { useReadingSession } from '../../../context/ReadingSessionContext';

const BASE64: any = (FileSystem as any).EncodingType?.Base64 ?? 'base64';

// 🔗 Match your server.js base
const API_BASE = process.env.EXPO_PUBLIC_API_BASE || 'http://localhost:3000';

type PlanRow = { key: string; label: string; bags: number; pricePerBag: number; subtotal: number };
type Plan = { code: string; title: string; rows: PlanRow[]; total: number; currency: string };

export default function RecommendationScreen() {
  const router = useRouter();
  const { result } = useReadingSession();

  const [loading, setLoading] = useState(true);
  const [plans, setPlans] = useState<Plan[]>([]);
  const [narrative, setNarrative] = useState<{ en: string; tl: string } | null>(null);
  const [currency, setCurrency] = useState('PHP');

  useEffect(() => {
    const TEN_MIN = 10 * 60 * 1000;
    if (!result || Date.now() - result.ts > TEN_MIN) {
      Alert.alert('No Sensor Data', 'Please connect to ESP32-NPK and take a reading first.');
      router.replace('/guest/screens/sensor-reading');
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const nValue = result?.n ?? 0;
  const pValue = result?.p ?? 0;
  const kValue = result?.k ?? 0;
  const phValue = result?.ph ?? 6.5;
  const phStatus = phValue < 5.5 ? 'Acidic' : phValue > 7.5 ? 'Alkaline' : 'Neutral';

  useEffect(() => {
    let canceled = false;
    const load = async () => {
      try {
        if (!result) return;
        const payload = { n: nValue, p: pValue, k: kValue, ph: phValue };
        const { data } = await axios.post(`${API_BASE}/api/recommend`, payload, { timeout: 10000 });
        if (canceled) return;
        if (!data?.ok) throw new Error('Bad response');
        setPlans(data.plans || []);
        setNarrative(data.narrative || null);
        setCurrency(data.plans?.[0]?.currency || 'PHP');
      } catch (e) {
        Alert.alert('Error', 'Failed to load recommendation. Please try again.');
      } finally {
        !canceled && setLoading(false);
      }
    };
    load();
    return () => { canceled = true; };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const handleSavePDF = async () => {
    try {
      const today = new Date();
      const formattedDate = today.toISOString().split('T')[0];
      const fileName = `FertiSense_${formattedDate}.pdf`;

      const plansHtml = plans.map((plan) => `
        <p><strong>${plan.title} - ${currency === 'PHP' ? '₱' : ''}${plan.total.toFixed(2)}</strong></p>
        <table>
          <tr><th>Fertilizer</th><th>Amount</th><th>Subtotal</th></tr>
          ${plan.rows.map(r =>
            `<tr><td>${r.label}</td><td>${r.bags} bags</td><td>${currency === 'PHP' ? '₱' : ''}${r.subtotal.toFixed(2)}</td></tr>`
          ).join('')}
        </table>
      `).join('');

      const htmlContent = `
        <html>
          <head>
            <meta charset="utf-8" />
            <style>
              body { font-family: Arial, sans-serif; padding: 20px; }
              h1 { color: #2e7d32; }
              p { margin-bottom: 8px; }
              .section { margin-top: 20px; }
              table { width: 100%; border-collapse: collapse; margin-top: 10px; }
              th, td { border: 1px solid #ccc; padding: 8px; text-align: center; }
              .footer { margin-top: 40px; font-size: 12px; color: #888; text-align: center; }
            </style>
          </head>
          <body>
            <h1>🌾 Fertilizer Recommendation Report</h1>
            <p><strong>📈 pH Level:</strong> ${phValue.toFixed(1)} (${phStatus})</p>

            <div class="section">
              <h3>📋 Recommendation</h3>
              <p>${narrative?.tl ?? ''}</p>
              <p><em>${narrative?.en ?? ''}</em></p>
            </div>

            <div class="section">
              <h3>🧪 Fertilizer Plans</h3>
              ${plansHtml}
            </div>

            <div class="footer">Report generated by FertiSense • ${formattedDate}</div>
          </body>
        </html>
      `;

      const { uri } = await Print.printToFileAsync({ html: htmlContent, base64: false });

      if (Platform.OS === 'android') {
        try {
          const SAF = (FileSystem as any).StorageAccessFramework;
          const perm = await SAF.requestDirectoryPermissionsAsync();
          if (perm?.granted && perm.directoryUri) {
            const base64 = await FileSystem.readAsStringAsync(uri, { encoding: BASE64 });
            const destUri = await SAF.createFileAsync(perm.directoryUri, fileName, 'application/pdf');
            await FileSystem.writeAsStringAsync(destUri, base64, { encoding: BASE64 });
            Alert.alert('✅ Saved', 'PDF saved to your chosen folder.');
            return;
          }
        } catch {}
      }

      if (await Sharing.isAvailableAsync()) {
        await Sharing.shareAsync(uri, { mimeType: 'application/pdf', dialogTitle: '📄 Share or Save Recommendation PDF' });
      } else {
        Alert.alert('✅ PDF Created', `File is at: ${uri}`);
      }
    } catch {
      Alert.alert('❌ PDF Error', 'Could not generate PDF. Try again.');
    }
  };

  if (loading) {
    return (
      <ScrollView contentContainerStyle={styles.container}>
        <Image source={require('../../../assets/images/fertisense-logo.png')} style={styles.logo} resizeMode="contain" />
        <Text style={{ textAlign: 'center' }}>Loading live recommendation…</Text>
      </ScrollView>
    );
  }

  const recommendationText = narrative?.tl ?? '';
  const englishText = narrative?.en ?? '';

  return (
    <ScrollView contentContainerStyle={styles.container}>
      <Image
        source={require('../../../assets/images/fertisense-logo.png')}
        style={styles.logo}
        resizeMode="contain"
      />

      {/* 📊 pH Result */}
      <View style={styles.phBox}>
        <Text style={styles.phLabel}>📊 pH Level Result:</Text>
        <Text style={styles.phValue}>{phValue.toFixed(1)} ({phStatus})</Text>
        <Text style={styles.phNote}>
          {phStatus === 'Acidic' && 'Soil is too acidic. Consider applying lime.'}
          {phStatus === 'Neutral' && 'Soil pH is optimal for most crops.'}
          {phStatus === 'Alkaline' && 'Soil is alkaline. May affect nutrient availability.'}
        </Text>
      </View>

      {/* 📝 Recommendation */}
      <View style={styles.recommendationBox}>
        <Text style={styles.recommendationTitle}>
          Rekomendasyon: <Text style={{ fontStyle: 'italic' }}>(Recommendation)</Text>
        </Text>
        <Text style={styles.recommendationText}>{recommendationText}</Text>
        <Text style={styles.englishText}>{englishText}</Text>
      </View>

      {/* ✅ Action Checklist */}
      <View style={styles.checkItem}>
        <Image source={require('../../../assets/images/checkmark.png')} style={styles.checkIcon} />
        <Text style={styles.checkText}>Mag-apply ayon sa napiling plano.</Text>
      </View>
      <View style={styles.checkItem}>
        <Image source={require('../../../assets/images/checkmark.png')} style={styles.checkIcon} />
        <Text style={styles.checkText}>I-monitor ang pH at moisture kung mayroon.</Text>
      </View>

      {/* Fertilizer Table */}
      <View style={styles.divider} />
      <Text style={styles.sectionTitle}>Fertilizer Recommendations</Text>

      {plans.map((plan) => (
        <View key={plan.code} style={styles.table}>
          <View style={styles.tableHeader}>
            <Text style={styles.tableTitle}>{plan.title}</Text>
            <Text style={styles.priceTag}>
              {currency === 'PHP' ? '₱' : ''}{plan.total.toFixed(2)}
            </Text>
          </View>

          <View style={styles.tableRow}>
            <Text style={styles.cellHeader}>Fertilizer</Text>
            <Text style={styles.cellHeader}>Bags</Text>
            <Text style={styles.cellHeader}>Subtotal</Text>
          </View>

          {plan.rows.map((r) => (
            <View key={r.key} style={styles.tableRow}>
              <Text style={styles.cell}>{r.label}</Text>
              <Text style={styles.cell}>{r.bags}</Text>
              <Text style={styles.cell}>
                {currency === 'PHP' ? '₱' : ''}{r.subtotal.toFixed(2)}
              </Text>
            </View>
          ))}
        </View>
      ))}

      {/* 📄 PDF Download */}
      <View style={styles.downloadToggle}>
        <Text style={styles.downloadLabel}>Save a copy of this report</Text>
        <TouchableOpacity onPress={handleSavePDF}>
          <Text style={styles.downloadButton}>📄 Download PDF</Text>
        </TouchableOpacity>
      </View>

      {/* 🔙 Back Home */}
      <TouchableOpacity style={styles.button} onPress={() => router.push('/guest/tabs/guest-home')}>
        <Text style={styles.buttonText}>Back to Home Screen</Text>
      </TouchableOpacity>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: { padding: 23, backgroundColor: '#fff', flexGrow: 1, paddingBottom: 80 },
  logo: { width: 200, height: 200, alignSelf: 'center', marginBottom: -30 },
  phBox: { backgroundColor: '#e8f5e9', padding: 14, borderRadius: 10, marginBottom: 16, alignItems: 'center' },
  phLabel: { fontSize: 14, color: '#2e7d32', fontWeight: 'bold' },
  phValue: { fontSize: 26, fontWeight: 'bold', color: '#1b5e20', marginVertical: 4 },
  phNote: { fontSize: 13, color: '#555', textAlign: 'center' },
  recommendationBox: { borderColor: '#4CAF50', borderWidth: 1.5, padding: 16, borderRadius: 10, marginBottom: 20, backgroundColor: '#f8fff9' },
  recommendationTitle: { fontSize: 16, fontWeight: 'bold', color: '#2e7d32', marginBottom: 8 },
  recommendationText: { fontSize: 14, marginBottom: 8, color: '#222' },
  englishText: { fontSize: 13, color: '#555', fontStyle: 'italic' },
  checkItem: { flexDirection: 'row', alignItems: 'center', borderColor: '#ccc', borderWidth: 1, borderRadius: 10, padding: 10, marginBottom: 12, backgroundColor: '#fdfdfd' },
  checkIcon: { width: 20, height: 20, marginRight: 10, resizeMode: 'contain' },
  checkText: { fontSize: 14, color: '#333' },
  divider: { height: 1, backgroundColor: '#000', marginVertical: 20, borderRadius: 8 },
  sectionTitle: { fontSize: 18, fontWeight: 'bold', textAlign: 'center', marginBottom: 12 },
  table: { marginBottom: 20, borderWidth: 1, borderColor: '#ccc', borderRadius: 8, overflow: 'hidden' },
  tableHeader: { flexDirection: 'row', justifyContent: 'space-between', backgroundColor: '#f0f0f0', padding: 10 },
  tableTitle: { fontSize: 14, fontWeight: 'bold' },
  priceTag: { backgroundColor: '#5D9239', color: '#fff', fontWeight: 'bold', paddingHorizontal: 12, paddingVertical: 4, borderRadius: 10, fontSize: 13 },
  tableRow: { flexDirection: 'row', borderTopWidth: 1, borderColor: '#ddd' },
  cellHeader: { flex: 1, padding: 10, fontWeight: 'bold', fontSize: 12, textAlign: 'center', backgroundColor: '#e8f5e9' },
  cell: { flex: 1, padding: 10, fontSize: 12, textAlign: 'center' },
  button: { backgroundColor: '#2e7d32', paddingVertical: 14, borderRadius: 50, marginTop: 20, marginBottom: 10 },
  buttonText: { color: '#fff', fontWeight: 'bold', textAlign: 'center', fontSize: 16 },
  downloadToggle: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 5, borderTopWidth: 3, borderColor: '#417d44ff', paddingVertical: 10 },
  downloadLabel: { color: '#444', fontSize: 13 },
  downloadButton: { fontSize: 15, color: '#550909', fontWeight: 'bold' },
});
